### PR TITLE
Custom output formatter

### PR DESCRIPTION
**Pull request by kpacha**
as requested at #92, this PR changes the rendering strategy so clients can inject the output format for each test

### CODE REVIEW

**Comment by kpacha** [comment]
ouch! the build failed because I'm using the new `strings.Builder` from 1.10.

Should I upgrade the golang version in the travis config or use any other method to build strings compatible with 1.9?

**Comment by kpacha** [comment]
@rakyll Why is taking so long to answer my question?

**Comment by rakyll** [comment]
Can you replace the use of strings.Builder and make sure it builds with Go 1.9?

**Comment by rakyll** [comment]
Thanks!

**Pull request merged**
